version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
        - echo Entered the install phase...
        - echo Logging in to Amazon ECR... 
        - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  pre_build:
    commands:
      - echo Nothing to do in prebuild phase
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - ./build_scripts/remote/build.sh
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - ./build_scripts/remote/push.sh
artifacts:
  files: /imageDetail.json
  discard-paths: yes