version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
        - echo Nothing to do in install phase
  pre_build:
    commands:
      - echo Nothing to do in prebuild phase
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Lambda zip payload
      - ./build_scripts/pipeline/build.sh full
  post_build:
    commands:
      - ls -la ./
      - echo Build completed on `date`
      - echo Pushing the Lambda zip payload
      - ./build_scripts/pipeline/publish.sh