# Generated by Django 3.0.3 on 2020-02-29 09:13

import os

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        superuser = User.objects.create_superuser(
            username=settings.DJANGO_SU_NAME,
            email=settings.DJANGO_SU_EMAIL,
            password=settings.DJANGO_SU_PASSWORD)

        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
